flaskblog/post/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, MultipleFileField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('제목', validators=[DataRequired()])
    content = TextAreaField('내용', validators=[DataRequired()])
    image_files = MultipleFileField('사진 추가', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('게시')


class CommentForm(FlaskForm):
    body = TextAreaField('댓글 추가', validators=[DataRequired()])
    submit = SubmitField('작성')

flaskblog/post/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment
from flaskblog.post.forms import PostForm, CommentForm
from flaskblog.user.utils import save_images


posts = Blueprint('posts', __name__) # 기존에 있던 변수나 함수 post랑 안 겹치게 설정

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image_files.data[0].filename: # form으로 들어온 파일의 파일 이름이 있을 때
            images = [save_images(image_file) for image_file in form.image_files.data]
            post = Post(title=form.title.data, content=form.content.data, image_files=images, author=current_user)
        else:
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index')) # blueprint_name.func으로 바꿔줌
    return render_template('create_post.html', title='New Post', form=form, legend='새 게시물')

@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id) # 해당 post_id가 없으면 404 페이지 리턴
    form = CommentForm()
    comments = Comment.query.filter_by(article=post).order_by(Comment.timestamp.desc()).all()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, writer=current_user, article=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added!", "success")
        return redirect(url_for('posts.post', post_id=post.id))
    return render_template('post.html', title=post.title, post=post, comments=comments, form=form)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: 
        abort(403) # 자신의 게시물이 아닐 시 403페이지 리턴
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.image_files.data[0].filename:
            images = [save_images(image_file) for image_file in form.image_files.data]
            post.image_files = images
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title # GET으로 접속했을 때 input의 value를 기존값으로 적용해놓음
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='게시물 수정')

@posts.route('/post/<int:post_id>/delete', methods=['POST']) # button을 통해서만 접근 가능
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: 
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

@posts.route('/post/<int:post_id>/update-comment/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def update_comment(post_id, comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.writer != current_user: 
        abort(403)
    form = CommentForm()
    if form.validate_on_submit():
        comment.body = form.body.data
        db.session.commit()
        flash('Your comment has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.body.data = comment.body
    return render_template('update_comment.html', title='Update Comment', form=form)

@posts.route('/post/<int:post_id>/delete-comment/<int:comment_id>')
@login_required
def delete_comment(post_id, comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.writer != current_user: 
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted!', 'success')
    return redirect(url_for('posts.post', post_id=post_id))

flaskblog/user/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt # init모듈의 함수는 디렉토리에서 바로 import
from flaskblog.models import User, Post, Comment
from flaskblog.user.forms import RegistrationForm, LoginForm, UpdateForm, ChangePasswordForm, RequestResetForm, ResetPasswordForm
from flaskblog.user.utils import save_image, send_email


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index')) # 로그인 되어있을 때 regitster로 접속하면 홈으로 이동
    form = RegistrationForm() 
    if form.validate_on_submit(): # POST의 유효성검사가 정상적으로 되었는지 확인
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') # 비밀번호 암호화
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {form.username.data}, your account has been created!', 'success') # f-string을 쓰면 {}안에 변수 넣어서 출력 가능. success는 bootstrap class
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') # account로 접속했을 때 login_required에 의해 로그인 페이지로 이동하면 url에 query string으로 ?next=%2Faccount가 붙어 있음. 로그인을 완료하면 account로 바로 이동하게 함. get을 쓰면 key가 없을 때 none을 반환하는데 []를 쓰면 에러 발생시킴
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route('/account', methods=['GET', 'POST'])
@login_required # 로그인 안 되어있을 때 account로 접속하면 에러 페이지 반환 -> init.py에서 반환 페이지 수정 가능
def account():
    form = UpdateForm()
    if form.validate_on_submit():
        image_file = save_image(form.image_file.data)
        current_user.image_file = image_file # current_user는 현재 접속중인 User객체를 가리킴
        db.session.commit()
        flash('Your profile image has been updated!', 'success')
        return redirect(url_for('users.account'))
    image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        current_user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed!', 'success')
        return redirect(url_for('users.account'))
    return render_template('password.html', title='Password', form=form)

@users.route('/user-posts/<username>') # uri에는 _보다 -사용
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_post.html', posts=posts, user=user)

@users.route('/posts-comment')
@login_required
def posts_comment():
    comment = Comment.query.filter_by(writer=current_user).order_by(Comment.timestamp.desc()).first()
    if not comment:
        return render_template('none.html', announcement='최근 단 댓글이 없습니다.')
    post = comment.article
    return redirect(url_for('posts.post', post_id=post.id))

@users.route('/reset-password', methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_email(user)
        flash('An email has been sent.', 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Reset Password', form=form)

@users.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token) # static 함수 호출
    if not user:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.request_reset'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Reset Password', form=form)

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
          <img class="rounded-circle account-img" src="{{ image_file }}">
          <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
            <a id="content-section" href="{{ url_for('users.password') }}">비밀번호 변경</a>
          </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"></legend>
                <div class="form-group">
                    <b>{{ form.image_file.label(class="form-control-label") }}</b>
                    {{ form.image_file(class="form-control-file") }}
                    {% if form.image_file.errors %}
                        {% for error in form.image_file.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.image_files.label(class="form-control-label") }}
                    {{ form.image_files(class="form-control-file") }}
                    {% if form.image_files.errors %}
                        {% for error in form.image_files.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/index.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %} <!--현재 page에 있는 item(post)들-->
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.image_file )}}" alt="profile image">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h4><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %} <!--전체 page 리스트-->
        {% if page %}
            {% if page == posts.page %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.index', page=page) }}">{{ page }}</a> <!--url_for속의 함수가 받는 매개변수가 없는데 인자를 보내면 query string으로 보냄-->
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.index', page=page) }}">{{ page }}</a>
            {% endif %}
        {% else %}
            ... <!--page에 none값이 오면 ...처리(먼 페이지 생략)-->
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    {% if title %}
        <title>Blog - {{ title }}</title>
    {% else %}
        <title>Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">My Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
            </div>
            <div class="navbar-nav">
              {% if current_user.is_authenticated %} <!--current_user로 현재 사용자 접근 가능-->
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.username }}</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            {% if current_user.is_authenticated %}
            <h4 class="mt-2 ml-1">{{ current_user.username }}님</h4>
            <p class="text-muted">
              <a class="ml-2" id="content-section" href="{{ url_for('users.account') }}">프로필</a>
              <ul class="list-group">
                <li class="list-group-item"><a class="list-group-item-light" id="content-section" href="{{ url_for('posts.post', post_id=2) }}">공지사항</a></li>
                <li class="list-group-item"><a class="list-group-item-light" id="content-section" href="{{ url_for('posts.create_post') }}">게시물 올리기</a></li>
                <li class="list-group-item"><a class="list-group-item-light" id="content-section" href="{{ url_for('users.user_posts', username=current_user.username) }}">내 게시물</a></li>
                <li class="list-group-item"><a class="list-group-item-light" id="content-section" href="{{ url_for('users.posts_comment') }}">최근 단 댓글</a></li>
                <li class="list-group-item list-group-item-light">기타</li>
              </ul>
            </p>
            {% else %}
            <h3>로그인 하세요</h3>
            <p class="text-muted">
              <ul class="list-group">
                <li class="list-group-item"><a class="list-group-item-light" id="content-section" href="{{ url_for('posts.post', post_id=2) }}">공지사항</a></li>
                <li class="list-group-item list-group-item-light">기타</li>
              </ul>
            </p>
            {% endif %}
          </div>
        </div>
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">로그인</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.request_reset') }}">비밀번호를 잊으셨나요?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/none.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        {{ announcement }}
    </div>
{% endblock content %}

flaskblog/templates/password.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">비밀번호 변경</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.image_file )}}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %X') }}</small>
                {% if post.author == current_user %}
                    <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">수정</a>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">삭제</button> <!--button태그는 input type='button'태그와 같은데 스타일 적용 가능-->
                    <!--눌렀을 때 alert 기능-->
                {% endif %}
            </div>
        <h4 class="article-title">{{ post.title }}</h4>
        <p class="article-content">{{ post.content }}</p>
        {% if post.image_files %}
            {% for image in post.image_files %}
                <img src="{{ url_for('static', filename='img/' + image )}}"><br><br>
            {% endfor %}
        {% endif %}
        </div>
    </article>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">댓글 {{ comments|count }}개</legend>
                <div class="form-group">
                    {{ form.body.label(class="form-control-label") }}
                    {% if form.body.errors %}
                        {{ form.body(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.body.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.is_authenticated %}
                            {{ form.body(class="form-control form-control-lg", placeholder="댓글을 작성하세요.") }}
                        {% else %}
                            {{ form.body(class="form-control form-control-lg", placeholder="댓글을 작성하려면 로그인을 해주세요.") }}
                        {% endif %}
                    {% endif %}
                </div>
                {% if current_user.is_authenticated %}
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                {% endif %}
            </fieldset>
        </form>
        {% for comment in comments %}
        <article class="media content-section comment-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + comment.writer.image_file )}}" alt="profile image">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=comment.writer.username) }}">{{ comment.writer.username }}</a>
                    <small class="text-muted">{{ comment.timestamp.strftime('%Y-%m-%d %X') }}</small>
                    {% if comment.writer == current_user %}
                        <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_comment', post_id=post.id, comment_id=comment.id) }}">수정</a>
                        <a class="btn btn-danger btn-sm" href="{{ url_for('posts.delete_comment', post_id=post.id, comment_id=comment.id) }}">삭제</a>
                    {% endif %}
                </div>
                <p class="article-content">{{ comment.body }}</p>
            </div>
        </article>
        {% endfor %}
    </div>
    <!--bootstrap alert-->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">게시물을 삭제하시겠습니까?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="삭제"> <!--url 이동하려면 a태그나 submit 사용-->
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/user_post.html
{% extends "layout.html" %}
{% block content %}
    <h2 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h2> <!--전체 page 게시물 수-->
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.image_file )}}" alt="profile image">
            <div class="media-body">
                <div class="article-metadata">
                    <span class="mr-2">{{ post.author.username }}</span>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h4><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
        {% if page %}
            {% if page == posts.page %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', page=page, username=user.username) }}">{{ page }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', page=page, username=user.username) }}">{{ page }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}